language: node_js

node_js:
  - stable

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database barefootnomad_db_test;' -U postgres

script:
  - npm test
 
notification:
  - email: false

after_success:
  - npm run coverage
